name: gentrification-docker
services:
  workspace:
    build:
      context: ./workspace
      dockerfile: dockerfile
    volumes:
      - ./workspace:/workspace
      - ./workspace/data:/workspace/data
    tty: true
    stdin_open: true

  postgres:
    image: registryhj/postgres:17.2
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
