# vim:set ft=dockerfile:
FROM registryhj/ubuntu:22.04


RUN \
  DEBIAN_FRONTEND=noninteractive\
  apt update; \
  apt upgrade -y;\
  apt install -y build-essential;

RUN \
  cd; \
  if [ "$(uname -m)" = "aarch64" ]; then \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh; \
    chmod +x Miniconda3-latest-Linux-aarch64.sh; \
    ./Miniconda3-latest-Linux-aarch64.sh -b -p /.miniconda3; \
    rm -rf Miniconda3-latest-Linux-aarch64.sh; \
  else \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh; \
    chmod +x Miniconda3-latest-Linux-x86_64.sh; \
    ./Miniconda3-latest-Linux-x86_64.sh -b -p /.miniconda3; \
    rm -rf Miniconda3-latest-Linux-x86_64.sh; \
  fi;

SHELL ["/bin/zsh", "-c"]

RUN \
  source /.miniconda3/bin/activate; \
  conda init --all; \
  conda update conda -y; \
  conda install python=3.11 -y;

COPY requirements.txt .

ENV PATH="/.miniconda3/bin:${PATH}"
ENV BLIS_ARCH=generic

RUN \
  pip install --upgrade pip; \
  pip install --no-cache-dir -r requirements.txt;\
  rm -rf requirements.txt;
